---
name: Magniv Bug report
description: Problems and issues with code in Magniv core
labels: ["kind:bug"]
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
        <img src='https://www.magniv.io/static/media/textlogo.e9b53078962edf01fb96e8f0eeab7880.svg' align='left' width='80'>
        Thank you for finding the time to report the problem!

        Note, you do not need to create an issue if you have a change ready to submit!

        You can open a [pull request](https://github.com/MagnivOrg/magniv-core/pulls) immediately instead.
        <br clear='left'/>"
      # yamllint enable rule:line-length
  - type: textarea
    attributes:
      label: What happened
      description: Describe what happened.
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened
    validations:
      required: true
  - type: textarea
    attributes:
      label: What you think should happen instead
      description: What do you think went wrong?
      placeholder: >
        Please explain why you think the behaviour is erroneous. It is extremely helpful if you copy&paste
        the fragment of logs showing the exact error messages or wrong behaviour and screenshots for
        UI problems or YouTube link to a video of you demonstrating the problem. You can include files by
        dragging and dropping them here.
  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        What should we do to reproduce the problem? If you are not able to provide a reproducible case,
        please open a instead.
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce the problem
        as minimally and precisely as possible. Keep in mind we do not have access to your cluster or DAGs.
        Remember that non-reproducible issues will be closed! Opening a discussion is recommended as a
        first step.
  - type: textarea
    attributes:
      label: Deployment details
      description: Additional description of your deployment.
      placeholder: >
        Enter any relevant details of your deployment. Especially version of your tools,
        software (docker-compose, helm, k8s, etc.), any customisation and configuration you added.
  - type: textarea
    attributes:
      label: Anything else
      description: Anything else we need to know?
      placeholder: >
        How often does this problem occur? (Once? Every time? Only when certain conditions are met?)
        Any relevant logs to include? Put them here inside fenced
        ``` ``` blocks or inside a foldable details tag if it's long:
        <details><summary>x.log</summary> lots of stuff </details>
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
