---
name: Magniv feature request
description: Suggest an idea for this project
labels: ["kind:feature"]
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
       <img src='https://www.magniv.io/static/media/textlogo.e9b53078962edf01fb96e8f0eeab7880.svg' align='left' width='180'>
        Thank you for finding the time to propose new feature!

        We really appreciate the community efforts to improve Magniv.

        Note, that you do not need to create an issue if you have a change ready to submit!

        You can open [Pull Request](https://github.com/MagnivOrg/magniv-core/pulls) immediately instead.
        <br clear='left'/>"

      # yamllint enable rule:line-length
  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature
  - type: textarea
    attributes:
      label: Use case/motivation
      description: What would you like to happen?
      placeholder: >
          Rather than telling us how you might implement this feature, try to take a
          step back and describe what you are trying to achieve.
  - type: textarea
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the feature.
      options:
        - label: Yes I am willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
