name: e2e-tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@master
        with:
          repository: MagnivOrg/magniv-repo-for-testing
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: working directory
        run: |
          ls
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install magniv
      - name: Magniv build
        run: |
          magniv-cli build
      - name: Magniv export
        run: |
          magniv-cli export
