name: Linting

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
      - name: Lint with flake8
        run: |
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=98 --statistics
      - name: Lint with black
        run: |
          black . --check --line-length=98
      - name: Lint with isort
        run: |
          isort . --check --profile black --line-length=98
